import { useMemo, useState } from "react";

type Product={id:number;name:string;category:string;price:number;rating:string;tone:"plum"|"terra"|"green"|"gold"};
const categories=["All","Fashion","Beauty","Home","Lifestyle","Gifts"];
const products:Product[]=[
{id:1,name:"Loom Woven Everyday Tote",category:"Fashion",price:18500,rating:"4.9",tone:"terra"},
{id:2,name:"Sandalwood + Vanilla Candle",category:"Beauty",price:12500,rating:"4.8",tone:"plum"},
{id:3,name:"Soft Leather Mini Bag",category:"Fashion",price:28500,rating:"4.9",tone:"green"},
{id:4,name:"Glow Body Care Set",category:"Beauty",price:22000,rating:"4.7",tone:"gold"},
{id:5,name:"Hand-finished Serving Tray",category:"Home",price:16000,rating:"4.8",tone:"terra"},
{id:6,name:"Weekend Self-care Box",category:"Gifts",price:24500,rating:"5.0",tone:"plum"},
{id:7,name:"Everyday Linen Shirt",category:"Fashion",price:19500,rating:"4.8",tone:"green"},
{id:8,name:"Calm Home Fragrance Duo",category:"Lifestyle",price:15000,rating:"4.9",tone:"gold"}];
const naira=(v:number)=>`₦${v.toLocaleString("en-NG")}`;
function ProductArt({tone}:{tone:Product["tone"]}){const fill={plum:"#43283A",terra:"#A95F4E",green:"#6E806A",gold:"#B18B55"}[tone];return <svg viewBox="0 0 240 220" role="img" aria-label="Product illustration" className="product-art"><rect width="240" height="220" rx="22" fill="#F2E8DC"/><circle cx="178" cy="55" r="42" fill="#E7D7C7"/><path d="M73 151c0-39 20-65 48-65h23c26 0 47 26 47 65v17H73z" fill={fill}/><path d="M99 91c2-23 13-36 30-36s28 13 30 36" fill="none" stroke="#201A1D" strokeWidth="7" strokeLinecap="round"/><rect x="89" y="168" width="61" height="10" rx="5" fill="#201A1D" opacity=".12"/></svg>}
function SearchIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.8" cy="10.8" r="6.8" fill="none" stroke="currentColor" strokeWidth="1.8"/><path d="m16 16 5 5" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/></svg>}
function BagIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 8h12l1 12H5z" fill="none" stroke="currentColor" strokeWidth="1.7"/><path d="M9 9V7a3 3 0 0 1 6 0v2" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round"/></svg>}
export function Index(){
const [category,setCategory]=useState("All"),[query,setQuery]=useState(""),[cart,setCart]=useState<number[]>([]),[checkoutOpen,setCheckoutOpen]=useState(false),[notice,setNotice]=useState("");
const visible=useMemo(()=>products.filter(p=>(category==="All"||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())),[category,query]);
function add(p:Product){setCart(items=>[...items,p.id]);setNotice(`${p.name} added to your bag`);window.setTimeout(()=>setNotice(""),2200)}
return <div className="market-shell">
<div className="announcement">Free delivery on orders over ₦50,000 <span>•</span> Shop with confidence</div>
<header className="site-header"><a href="#top" className="brand"><span className="brand-mark">M</span><span>MAH-YAH <b>MARKET</b></span></a><nav className="desktop-nav"><a href="#shop">Shop</a><a href="#categories">Categories</a><a href="#story">Our story</a><a href="#support">Support</a></nav><div className="header-actions"><button className="icon-button" aria-label="Search" onClick={()=>document.getElementById("shop")?.scrollIntoView({behavior:"smooth"})}><SearchIcon/></button><button className="bag-button" onClick={()=>setCheckoutOpen(true)}><BagIcon/><span>Bag</span>{cart.length>0&&<em>{cart.length}</em>}</button></div></header>
<main id="top">
<section className="hero wrap"><div className="hero-copy"><p className="eyebrow">A better way to shop local</p><h1>Good finds.<br/><i>One beautiful market.</i></h1><p className="hero-text">Discover fashion, beauty, home and lifestyle pieces from a carefully selected collection. Simple browsing, clear prices and a checkout built for Nigeria.</p><div className="hero-actions"><a className="cta-primary" href="#shop">Shop the collection <span>↗</span></a><a className="cta-secondary" href="#categories">Explore categories</a></div><div className="hero-note"><span className="check">✓</span> Secure Paystack checkout <span className="dot">•</span> Delivery details collected at checkout</div></div><div className="hero-visual"><div className="hero-card"><div className="hero-stamp">CURATED<br/><strong>FOR YOU</strong></div><div className="hero-orbit one"/><div className="hero-orbit two"/><div className="hero-bag-shape"/><div className="hero-candle"/><div className="hero-label"><small>FEATURED EDIT</small><strong>Everyday pieces<br/>with character.</strong></div></div><div className="floating-card"><span>4.9 ★</span><strong>Loved by shoppers</strong><small>Fresh picks added regularly</small></div></div></section>
<section className="trust-strip"><div><strong>Secure checkout</strong><span>Powered by Paystack</span></div><div><strong>Delivery-ready</strong><span>Share your location at checkout</span></div><div><strong>Need help?</strong><span>Chat with us on WhatsApp</span></div></section>
<section id="categories" className="wrap categories-section"><div className="section-head"><div><p className="eyebrow">Shop by mood</p><h2>Find your next favourite.</h2></div><p>Browse the collection by category, then add your picks to one simple bag.</p></div><div className="category-grid">{categories.slice(1).map((item,i)=><button key={item} className={`category-tile tile-${i+1}`} onClick={()=>{setCategory(item);document.getElementById("shop")?.scrollIntoView({behavior:"smooth"})}}><span>0{i+1}</span><strong>{item}</strong><small>Explore collection ↗</small></button>)}</div></section>
<section id="shop" className="wrap shop-section"><div className="shop-top"><div><p className="eyebrow">The collection</p><h2>Fresh from the market.</h2></div><div className="search-wrap"><SearchIcon/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products" aria-label="Search products"/></div></div><div className="filter-row">{categories.map(item=><button key={item} className={category===item?"filter active":"filter"} onClick={()=>setCategory(item)}>{item}</button>)}<span className="result-count">{visible.length} products</span></div><div className="product-grid">{visible.map(p=><article className="product-card" key={p.id}><div className={`product-image ${p.tone}`}><ProductArt tone={p.tone}/><span className="product-badge">New</span><button className="quick-add" onClick={()=>add(p)} aria-label={`Add ${p.name} to bag`}>+</button></div><div className="product-info"><div className="product-meta"><span>{p.category}</span><span>★ {p.rating}</span></div><h3>{p.name}</h3><div className="product-bottom"><strong>{naira(p.price)}</strong><button onClick={()=>add(p)}>Add to bag</button></div></div></article>)}</div>{visible.length===0&&<div className="empty-state"><strong>No products found.</strong><span>Try another search or category.</span></div>}</section>
<section id="story" className="story-section wrap"><div className="story-art"><div className="story-circle"/><div className="story-card small"><span>LOCAL</span><strong>+</strong><span>CURATED</span></div><div className="story-card large"><small>THE MAH-YAH EDIT</small><strong>Pieces that<br/>feel like you.</strong></div></div><div className="story-copy"><p className="eyebrow">More than a storefront</p><h2>Shopping should feel as good as finding something special.</h2><p>MAH-YAH MARKET brings the ease of a modern online shop to a collection that still feels personal. The experience is designed to make discovery easy, trust visible and checkout straightforward.</p><div className="story-points"><div><strong>01</strong><span>Curated selection</span></div><div><strong>02</strong><span>Clear Naira pricing</span></div><div><strong>03</strong><span>Simple local delivery</span></div></div></div></section>
<section id="support" className="benefits wrap"><div className="benefit"><span>01</span><strong>Easy to browse</strong><p>Clear categories and search help customers get to the right product quickly.</p></div><div className="benefit"><span>02</span><strong>Easy to trust</strong><p>Prices, ratings, delivery information and support are visible before checkout.</p></div><div className="benefit"><span>03</span><strong>Easy to buy</strong><p>A clean cart flow leads naturally into a familiar Paystack payment experience.</p></div></section>
<section className="final-cta wrap"><div><p className="eyebrow">Ready when you are</p><h2>Bring your next find home.</h2><p>Browse the collection or message the team if you need help choosing.</p></div><div className="final-actions"><a className="cta-primary light" href="#shop">Start shopping <span>↗</span></a><a className="whatsapp" href="https://wa.me/2340000000000" target="_blank" rel="noreferrer">WhatsApp concierge</a></div></section>
</main>
<footer><div className="footer-main wrap"><div><a className="brand footer-brand" href="#top"><span className="brand-mark">M</span><span>MAH-YAH <b>MARKET</b></span></a><p>A modern marketplace concept built around discovery, trust and easy checkout.</p></div><div className="footer-col"><strong>Shop</strong><a href="#shop">All products</a><a href="#categories">Categories</a><a href="#shop">New arrivals</a></div><div className="footer-col"><strong>Help</strong><a href="#support">Delivery</a><a href="#support">Payments</a><a href="#support">Contact us</a></div><div className="footer-col"><strong>Payment</strong><span className="paystack-pill">Paystack</span><small>Secure online checkout</small></div></div><div className="footer-bottom wrap"><span>© 2026 MAH-YAH MARKET</span><span>Designed as a storefront concept</span></div></footer>
{notice&&<div className="toast" role="status">✓ {notice}</div>}
{checkoutOpen&&<div className="modal-backdrop" onClick={()=>setCheckoutOpen(false)}><div className="checkout-modal" role="dialog" aria-modal="true" aria-labelledby="checkout-title" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setCheckoutOpen(false)} aria-label="Close">×</button><p className="eyebrow">Your bag</p><h2 id="checkout-title">Ready for checkout.</h2>{cart.length===0?<p>Your bag is empty. Add a product to preview the checkout experience.</p>:<p>You have {cart.length} item{cart.length===1?"":"s"} in your bag.</p>}<div className="checkout-summary"><span>Payment</span><strong>Paystack</strong></div><button className="checkout-button" disabled={cart.length===0}>Continue to Paystack</button><small>This sample uses a preview checkout. Payment credentials can be connected when the final store is ready.</small></div></div>}
</div>}
