import { useMemo, useState } from "react";

type Product={id:number;name:string;category:string;price:number;oldPrice?:number;rating:string;verified?:boolean;deal?:string;art:string};
const categories=["All","Phones & Tablets","Computers","TV & Audio","Appliances","Accessories"];
const products:Product[]=[
{id:1,name:"Itel 8KG Front Load Automatic Washing Machine",category:"Appliances",price:420000,oldPrice:450000,rating:"4.9",verified:true,deal:"7% OFF",art:"washer"},
{id:2,name:"Itel Split Inverter Air Conditioner",category:"Appliances",price:385000,rating:"4.8",verified:true,art:"ac"},
{id:3,name:"Smart Android LED Television",category:"TV & Audio",price:285000,rating:"4.8",verified:true,art:"tv"},
{id:4,name:"Wireless Bluetooth Speaker",category:"TV & Audio",price:68500,rating:"4.7",verified:true,art:"speaker"},
{id:5,name:"Fast-Charge Power Bank 20,000mAh",category:"Accessories",price:38500,rating:"4.9",verified:true,deal:"HOT DEAL",art:"power"},
{id:6,name:"Android Smartphone — 128GB",category:"Phones & Tablets",price:195000,rating:"4.8",verified:true,art:"phone"},
{id:7,name:"Everyday Laptop Backpack",category:"Computers",price:42000,rating:"4.7",verified:true,art:"bag"},
{id:8,name:"Wireless Keyboard & Mouse Combo",category:"Computers",price:32500,rating:"4.8",verified:true,art:"keyboard"}];
const naira=(v:number)=>`₦${v.toLocaleString("en-NG")}`;
function ProductArt({kind}:{kind:string}){return <svg viewBox="0 0 400 300" className="product-art" role="img" aria-label="Product illustration">
<rect width="400" height="300" fill="#17191C"/>
{kind==="washer"&&<><circle cx="205" cy="156" r="82" fill="#E8EAEC"/><circle cx="205" cy="156" r="58" fill="#27323A"/><circle cx="205" cy="156" r="45" fill="#0D1114"/><rect x="120" y="48" width="170" height="32" rx="8" fill="#E8EAEC"/><circle cx="145" cy="64" r="7" fill="#D86B35"/><text x="166" y="69" fill="#34383C" fontSize="13" fontFamily="Arial">8KG • FRONT LOAD</text></>}
{kind==="ac"&&<><rect x="65" y="92" width="270" height="112" rx="14" fill="#F0F1F2"/><rect x="82" y="116" width="236" height="56" rx="8" fill="#D9DDE0"/><path d="M105 140h190" stroke="#A8B0B5" strokeWidth="5" strokeDasharray="9 9"/><circle cx="290" cy="103" r="6" fill="#D86B35"/><text x="90" y="190" fill="#5B6166" fontSize="12" fontFamily="Arial">INVERTER • SPLIT AC</text></>}
{kind==="tv"&&<><rect x="62" y="62" width="276" height="170" rx="8" fill="#090B0D" stroke="#7E858A" strokeWidth="3"/><rect x="76" y="76" width="248" height="142" fill="#252D35"/><path d="M105 178c35-48 62-47 93-10 34-48 65-42 97 5" fill="none" stroke="#D86B35" strokeWidth="7"/><rect x="180" y="232" width="50" height="9" rx="4" fill="#858B90"/></>}
{kind==="speaker"&&<><rect x="128" y="48" width="144" height="210" rx="24" fill="#252A2E"/><circle cx="200" cy="116" r="38" fill="#0C0F11" stroke="#D86B35" strokeWidth="5"/><circle cx="200" cy="116" r="13" fill="#D86B35"/><circle cx="200" cy="198" r="25" fill="#0C0F11" stroke="#777F85" strokeWidth="4"/></>}
{kind==="power"&&<><rect x="128" y="46" width="144" height="210" rx="18" fill="#F1F2F3"/><rect x="154" y="78" width="92" height="34" rx="7" fill="#1E252A"/><text x="169" y="101" fill="#D86B35" fontSize="14" fontFamily="Arial">20,000</text><circle cx="200" cy="166" r="34" fill="#D86B35"/><path d="M200 142v48M176 166h48" stroke="#fff" strokeWidth="5"/></>}
{kind==="phone"&&<><rect x="137" y="28" width="126" height="244" rx="24" fill="#DDE1E4"/><rect x="147" y="45" width="106" height="204" rx="17" fill="#1A252C"/><circle cx="200" cy="144" r="45" fill="#273841"/><circle cx="186" cy="130" r="13" fill="#D86B35"/><circle cx="214" cy="130" r="13" fill="#9AA4A9"/><rect x="185" y="220" width="30" height="5" rx="2" fill="#7C858A"/></>}
{kind==="bag"&&<><path d="M102 94h196l-18 166H120z" fill="#4A3E36"/><path d="M150 96c0-65 100-65 100 0" fill="none" stroke="#D86B35" strokeWidth="13"/><rect x="133" y="138" width="134" height="9" rx="4" fill="#75665A"/></>}
{kind==="keyboard"&&<><rect x="62" y="88" width="276" height="126" rx="14" fill="#E7E9EA"/>{Array.from({length:24},(_,i)=><rect key={i} x={82+(i%8)*30} y={108+Math.floor(i/8)*29} width="22" height="18" rx="3" fill="#7A8186"/>)}<rect x="142" y="195" width="116" height="8" rx="4" fill="#7A8186"/></>}
</svg>}
function SearchIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.8" cy="10.8" r="6.8" fill="none" stroke="currentColor" strokeWidth="1.8"/><path d="m16 16 5 5" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/></svg>}
function BagIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 8h12l1 12H5z" fill="none" stroke="currentColor" strokeWidth="1.7"/><path d="M9 9V7a3 3 0 0 1 6 0v2" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round"/></svg>}
export function Index(){
const [category,setCategory]=useState("All"),[query,setQuery]=useState(""),[cart,setCart]=useState<number[]>([]),[checkoutOpen,setCheckoutOpen]=useState(false),[notice,setNotice]=useState("");
const visible=useMemo(()=>products.filter(p=>(category==="All"||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())),[category,query]);
function add(p:Product){setCart(items=>[...items,p.id]);setNotice(`${p.name} added to your bag`);window.setTimeout(()=>setNotice(""),2200)}
return <div className="market-shell">
<div className="announcement"><strong>MAH-YAH MARKET</strong><span>•</span> Quality gadgets & electronics <span>•</span> Nationwide delivery</div>
<header className="site-header"><a href="#top" className="brand"><span className="brand-mark">M</span><span>MAH-YAH <b>MARKET</b></span></a><nav className="desktop-nav"><a href="#shop">Shop</a><a href="#categories">Categories</a><a href="#deals">Deals</a><a href="#support">Support</a></nav><div className="header-actions"><button className="icon-button" aria-label="Search" onClick={()=>document.getElementById("shop")?.scrollIntoView({behavior:"smooth"})}><SearchIcon/></button><button className="bag-button" onClick={()=>setCheckoutOpen(true)}><BagIcon/><span>Cart</span>{cart.length>0&&<em>{cart.length}</em>}</button></div></header>
<main id="top">
<section className="hero wrap"><div className="hero-copy"><p className="eyebrow">Gadgets. Appliances. Everyday tech.</p><h1>Everything you need.<br/><i>One trusted market.</i></h1><p className="hero-text">Shop phones, computers, TVs, audio, appliances and accessories with clear Naira prices, straightforward delivery and a checkout designed for Nigeria.</p><div className="hero-search"><SearchIcon/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="What are you looking for?" aria-label="Search the marketplace"/></div><div className="hero-actions"><a className="cta-primary" href="#shop">Shop gadgets <span>↗</span></a><a className="cta-secondary" href="#categories">Browse categories</a></div><div className="hero-note"><span className="check">✓</span> Secure Paystack checkout <span className="dot">•</span> Nationwide delivery</div></div><div className="hero-visual"><div className="hero-panel"><div className="hero-panel-top"><span>FEATURED DEAL</span><strong>ITEL</strong></div><div className="hero-product"><ProductArt kind="washer"/></div><div className="hero-product-copy"><div><small>8KG FRONT LOAD</small><strong>Itel Washing Machine</strong></div><b>₦420,000</b></div></div><div className="deal-float"><span>7% OFF</span><strong>₦450,000 → ₦420,000</strong><small>Limited marketplace deal</small></div></div></section>
<section className="trust-strip"><div><strong>Verified listings</strong><span>Shop with clearer product information</span></div><div><strong>Paystack checkout</strong><span>Familiar, secure online payments</span></div><div><strong>Nationwide delivery</strong><span>Delivery details confirmed at checkout</span></div></section>
<section id="categories" className="wrap categories-section"><div className="section-head"><div><p className="eyebrow">Shop by category</p><h2>Find the right tech faster.</h2></div><p>From everyday accessories to major home appliances, browse the marketplace by what you actually need.</p></div><div className="category-grid">{categories.slice(1).map((item,i)=><button key={item} className={`category-tile tile-${i+1}`} onClick={()=>{setCategory(item);document.getElementById("shop")?.scrollIntoView({behavior:"smooth"})}}><span>0{i+1}</span><strong>{item}</strong><small>Shop now ↗</small></button>)}</div></section>
<section id="deals" className="deal-section wrap"><div className="deal-copy"><p className="eyebrow">Featured deal</p><h2>Big appliance.<br/>Better price.</h2><p>The Itel 8KG Front Load Automatic Washing Machine is now listed at <strong>₦420,000</strong>, reduced from ₦450,000.</p><button className="cta-primary" onClick={()=>{setCategory("Appliances");document.getElementById("shop")?.scrollIntoView({behavior:"smooth"})}}>Shop appliance deals <span>↗</span></button></div><div className="deal-art"><ProductArt kind="washer"/><div className="deal-badge">7% OFF</div></div></section>
<section id="shop" className="wrap shop-section"><div className="shop-top"><div><p className="eyebrow">The marketplace</p><h2>Popular gadgets & electronics.</h2></div><div className="search-wrap"><SearchIcon/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products" aria-label="Search products"/></div></div><div className="filter-row">{categories.map(item=><button key={item} className={category===item?"filter active":"filter"} onClick={()=>setCategory(item)}>{item}</button>)}<span className="result-count">{visible.length} products</span></div><div className="product-grid">{visible.map(p=><article className="product-card" key={p.id}><div className="product-image"><ProductArt kind={p.art}/>{p.deal&&<span className="product-badge">{p.deal}</span>}{p.verified&&<span className="verified-badge">✓ Verified</span>}<button className="quick-add" onClick={()=>add(p)} aria-label={`Add ${p.name} to cart`}>+</button></div><div className="product-info"><div className="product-meta"><span>{p.category}</span><span>★ {p.rating}</span></div><h3>{p.name}</h3><div className="product-bottom"><div><strong>{naira(p.price)}</strong>{p.oldPrice&&<del>{naira(p.oldPrice)}</del>}</div><button onClick={()=>add(p)}>Add to cart</button></div></div></article>)}</div>{visible.length===0&&<div className="empty-state"><strong>No products found.</strong><span>Try another search or category.</span></div>}</section>
<section id="support" className="support-section wrap"><div><p className="eyebrow">Built around the customer</p><h2>Clear products. Clear prices. Easy checkout.</h2><p>MAH-YAH MARKET is designed as a focused electronics storefront: customers can discover products, compare prices, see delivery/payment cues and move into a familiar Paystack checkout without unnecessary friction.</p></div><div className="support-grid"><div><span>01</span><strong>Product discovery</strong><p>Search, categories, deals and filters keep a large gadget catalogue easy to navigate.</p></div><div><span>02</span><strong>Payment ready</strong><p>Paystack is presented clearly as the primary online checkout option.</p></div><div><span>03</span><strong>WhatsApp support</strong><p>Customers can reach the store directly for product questions and purchase assistance.</p></div><div><span>04</span><strong>Delivery across Nigeria</strong><p>Delivery information is part of the buying journey rather than hidden after purchase.</p></div></div></section>
<section className="final-cta wrap"><div><p className="eyebrow">MAH-YAH MARKET</p><h2>Shop smarter. Get the right gadget.</h2><p>A marketplace experience made for phones, electronics, appliances and everyday tech.</p></div><div className="final-actions"><a className="cta-primary light" href="#shop">Start shopping <span>↗</span></a><a className="whatsapp" href="https://wa.me/2349152122459" target="_blank" rel="noreferrer">Chat on WhatsApp</a></div></section>
</main>
<footer><div className="footer-main wrap"><div><a className="brand footer-brand" href="#top"><span className="brand-mark">M</span><span>MAH-YAH <b>MARKET</b></span></a><p>Gadgets, electronics and appliances with a clean marketplace experience built for Nigerian shoppers.</p></div><div className="footer-col"><strong>Shop</strong><a href="#shop">All products</a><a href="#categories">Categories</a><a href="#deals">Deals</a></div><div className="footer-col"><strong>Customer care</strong><a href="#support">Delivery</a><a href="#support">Payments</a><a href="https://wa.me/2349152122459">WhatsApp</a></div><div className="footer-col"><strong>Payment</strong><span className="paystack-pill">Paystack</span><small>Secure online checkout</small></div></div><div className="footer-bottom wrap"><span>© 2026 MAH-YAH MARKET</span><span>Gadgets • Electronics • Appliances</span></div></footer>
{notice&&<div className="toast" role="status">✓ {notice}</div>}
{checkoutOpen&&<div className="modal-backdrop" onClick={()=>setCheckoutOpen(false)}><div className="checkout-modal" role="dialog" aria-modal="true" aria-labelledby="checkout-title" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setCheckoutOpen(false)} aria-label="Close">×</button><p className="eyebrow">Your cart</p><h2 id="checkout-title">Ready for checkout.</h2>{cart.length===0?<p>Your cart is empty. Add a product to preview the checkout experience.</p>:<p>You have {cart.length} item{cart.length===1?"":"s"} in your cart.</p>}<div className="checkout-summary"><span>Payment</span><strong>Paystack</strong></div><button className="checkout-button" disabled={cart.length===0}>Continue to Paystack</button><small>This sample uses a preview checkout. Live payment credentials can be connected when the final store is ready.</small></div></div>}
</div>}
